import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readdirSync, rmSync, writeFileSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { zodToJsonSchema } from 'zod-to-json-schema';
import { loadRegistry } from './load-registry.js';

// docs/architecture/05-jobs.md: "Python schemas are generated from TS Zod
// (JSON Schema → datamodel-code-generator). Don't hand-write Pydantic."
//
// This script walks the registered jobs, emits one JSON Schema per
// payload, and shells out to `uvx datamodel-code-generator` to produce
// Pydantic models under services/worker-py/jobs_schemas/. CI calls
// codegen-drift.ts to fail PRs that didn't regenerate.

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..', '..');
const outDir = resolve(repoRoot, 'services', 'worker-py', 'jobs_schemas');

export async function generate(targetDir = outDir): Promise<void> {
  mkdirSync(targetDir, { recursive: true });
  const tmp = mkdtempSync(resolve(tmpdir(), 'jobs-codegen-'));
  try {
    const registry = await loadRegistry();
    const jobs = registry.list();

    for (const job of jobs) {
      const schema = zodToJsonSchema(job.payload, { name: pascalCase(job.name) });
      writeFileSync(resolve(tmp, `${job.name}.json`), JSON.stringify(schema, null, 2));
    }

    if (jobs.length === 0) {
      // Still emit an __init__.py so the package is importable.
      writeFileSync(resolve(targetDir, '__init__.py'), '# generated by packages/jobs/scripts/generate-python-schemas.ts\n');
      return;
    }

    // datamodel-code-generator reads a directory of JSON Schema files and
    // emits a Pydantic module tree.
    execFileSync(
      'uvx',
      [
        '--quiet',
        'datamodel-code-generator',
        '--input',
        tmp,
        '--input-file-type',
        'jsonschema',
        '--output',
        targetDir,
        '--output-model-type',
        'pydantic_v2.BaseModel',
        '--use-double-quotes',
        '--field-constraints',
      ],
      { stdio: ['ignore', 'inherit', 'inherit'] },
    );

    // Idempotency: prepend a generated-from header to every file.
    for (const f of readdirSync(targetDir)) {
      if (!f.endsWith('.py')) continue;
      const p = resolve(targetDir, f);
      const body = readFileSync(p, 'utf8');
      if (!body.startsWith('# generated')) {
        writeFileSync(p, `# generated from packages/jobs Zod payloads — do not edit\n${body}`, 'utf8');
      }
    }
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

function pascalCase(name: string): string {
  return name
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((s) => s[0]!.toUpperCase() + s.slice(1))
    .join('');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  await generate();
}
