#!/usr/bin/env -S tsx
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describeSchema } from '../packages/env/src/describe.js';
import { webSchema } from '../packages/env/src/web.schema.js';
import { adminSchema } from '../packages/env/src/admin.schema.js';
import { workerNodeSchema } from '../packages/env/src/worker-node.schema.js';
import { workerPySchema } from '../packages/env/src/worker-py.schema.js';

// docs/architecture/12-local-dev.md — canonical one-command bootstrap.
//
// Idempotent. Re-running picks up newly-required env vars from packages/env
// schemas and surfaces them; existing values are never overwritten.

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');

function run(label: string, file: string, args: string[]): void {
  console.warn(`▸ ${label}`);
  execFileSync(file, args, { cwd: repoRoot, stdio: 'inherit' });
}

function readSupabaseStatus(): Map<string, string> {
  const raw = execFileSync('pnpm', ['exec', 'supabase', 'status', '-o', 'env'], {
    cwd: repoRoot,
    encoding: 'utf8',
  });
  const out = new Map<string, string>();
  for (const line of raw.split('\n')) {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)="(.*)"$/);
    if (m && m[1]) out.set(m[1], m[2] ?? '');
  }
  return out;
}

type Target = {
  schema: Parameters<typeof describeSchema>[0];
  envPath: string;
};

const targets: Target[] = [
  { schema: webSchema, envPath: 'apps/web/.env.local' },
  { schema: adminSchema, envPath: 'apps/admin/.env.local' },
  { schema: workerNodeSchema, envPath: 'services/worker-node/.env.local' },
  { schema: workerPySchema, envPath: 'services/worker-py/.env.local' },
];

function writeEnvLocal(target: Target, supabase: Map<string, string>): void {
  const path = resolve(repoRoot, target.envPath);
  const existing = new Map<string, string>();
  if (existsSync(path)) {
    for (const line of readFileSync(path, 'utf8').split('\n')) {
      const m = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
      if (m && m[1]) existing.set(m[1], m[2] ?? '');
    }
  }

  const lines: string[] = [
    `# Generated by scripts/setup.ts — re-run \`pnpm setup\` to refresh missing vars.`,
    '',
  ];
  const missing: string[] = [];
  for (const v of describeSchema(target.schema)) {
    if (existing.has(v.name)) {
      lines.push(`${v.name}=${existing.get(v.name)}`);
      continue;
    }
    // Defaults sourced from `supabase status` for the obvious keys.
    let value = '';
    if (v.name === 'SUPABASE_URL' || v.name === 'NEXT_PUBLIC_SUPABASE_URL') {
      value = supabase.get('API_URL') ?? supabase.get('SUPABASE_URL') ?? '';
    } else if (v.name === 'SUPABASE_SERVICE_ROLE_KEY') {
      value = supabase.get('SERVICE_ROLE_KEY') ?? '';
    } else if (v.name === 'NEXT_PUBLIC_SUPABASE_ANON_KEY') {
      value = supabase.get('ANON_KEY') ?? '';
    } else if (v.name === 'WORKER_DATABASE_URL' || v.name === 'ADMIN_DATABASE_URL') {
      value = supabase.get('DB_URL') ?? '';
    } else if (v.name === 'SMTP_HOST') {
      value = '127.0.0.1';
    } else if (v.name === 'SMTP_PORT') {
      value = '54425';
    } else {
      value = v.example ?? '';
    }
    if (v.required && !value) missing.push(v.name);
    lines.push(`${v.name}=${value}`);
  }

  writeFileSync(path, lines.join('\n') + '\n', 'utf8');
  console.warn(`  wrote ${target.envPath}` + (missing.length > 0 ? ` (fill in: ${missing.join(', ')})` : ''));
}

async function main(): Promise<void> {
  run('pnpm install', 'pnpm', ['install', '--frozen-lockfile']);
  run('supabase start', 'pnpm', ['exec', 'supabase', 'start']);
  run('supabase db reset', 'pnpm', ['exec', 'supabase', 'db', 'reset']);
  run('pnpm db:types', 'pnpm', ['db:types']);
  run('pnpm env:example', 'pnpm', ['env:example']);

  const status = readSupabaseStatus();
  for (const target of targets) writeEnvLocal(target, status);

  console.warn('\n✔ setup complete — `pnpm dev` to run the apps and workers.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
